{% set version = "0.5.12" %}

package:
  name: lap
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/l/lap/lap-{{ version }}.tar.gz
  sha256: 570b414ea7ae6c04bd49d0ec8cdac1dc5634737755784d44e37f9f668bab44fd

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - lap

about:
  home: https://github.com/gatagat/lap
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Linear Assignment Problem solver (LAPJV/LAPMOD)'
  dev_url: https://github.com/gatagat/lap

extra:
  recipe-maintainers:
    - primozgodec
